# Generated by Django 3.2.11 on 2024-04-13 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش')),
                ('order_code', models.CharField(default='antomi4530454', max_length=50, unique=True, verbose_name='کد سفارش')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('invoice_amount', models.IntegerField(default=0, verbose_name='مبلغ فاکتور')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='accounts.customer', verbose_name='مشتری/کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_state_title', models.CharField(max_length=50, verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'وضعیت های سفارش',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_title', models.CharField(max_length=50, verbose_name='نوع پرداخت')),
            ],
            options={
                'verbose_name': 'نوع پرداخت',
                'verbose_name_plural': 'انواع روش پرداخت',
            },
        ),
        migrations.CreateModel(
            name='orderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('qty', models.IntegerField(default=1, verbose_name='تعداد')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_details', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش',
                'verbose_name_plural': 'جزئیات سفارش ها',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstate', verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.paymenttype', verbose_name='روش پرداخت'),
        ),
    ]
