# Generated by Django 3.2.11 on 2024-04-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپیگیری')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد وضعیت')),
                ('invoice_amount', models.IntegerField(default=0, verbose_name='مبلغ فاکتور')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='accounts.customer', verbose_name='مشتری/کاربر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
