# Generated by Django 3.2.11 on 2024-04-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.IntegerField(verbose_name='قیمت فروش')),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='products.product', verbose_name='محصول')),
                ('user_registred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'انبار فروش محصول',
                'verbose_name_plural': 'انبار فروش محصولات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.IntegerField(verbose_name='قیمت خرید')),
                ('qty', models.PositiveIntegerField(verbose_name='تعداد')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to='products.product', verbose_name='محصول')),
                ('user_registred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'انبار خرید محصول',
                'verbose_name_plural': 'انبار خرید محصولات',
            },
        ),
    ]
